# The MIT License (MIT)
#
# Copyright © 2024 The GHDL Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the “Software”), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
name: Setup GHDL
branding:
  icon: play
  color: gray-dark
description: Install and setup GHDL downloaded from GHDL's release pages at GitHub.
author: Patrick Lehmann (@Paebbels)

inputs:
  version:
    description: |
      A tagged GHDL version starting at `v5.0.0` or `nightly`.
    type: string
    required: false
    default: 'nightly'
  backend:
    description: |
      GHDL backend: `llvm`, `llvm-jit`, `mcode`, `gcc`.
    type: string
    required: false
    default: 'mcode'
  runtime:
    description: |
      If runner OS is Windows, a MSYS2 runtime can be selected (`mingw64`, `ucrt64`). If not set, Windows native is used (not MSYS2 environment).
    type: string
    required: false
    default: ''
  install-directory:
    description: |
      Local installation directory, in case an archive asset is downloaded and extracted.
    type: string
    required: false
    default: 'install'
  investigate:
    description: |
      If enabled, more details are printed and check the GHDL installation is checked.
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Variables
      id: variables
      shell: bash
      run: |
        tee "${GITHUB_OUTPUT}" <<EOF
        latest-version=5.0.0
        latest-version-msys2=5.0.0-1
        nightly-version=5.0.0-dev
        nightly-version-msys2=5.0.0.dev-1
        EOF

    - name: Download and install GHDL on Ubuntu 2024.04 (x86-64)
      id: ubuntu
      if: runner.os == 'Linux' && runner.arch == 'X64'
      shell: bash
      run: |
        # Download and install GHDL on Ubuntu 2024.04 (x86-64)
        ANSI_LIGHT_BLUE="\e[94m"
        ANSI_NOCOLOR=$'\x1b[0m'

        source /etc/lsb-release

        if [[ "${DISTRIB_RELEASE}" != "24.04" ]]; then
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported Ubuntu version '${DISTRIB_RELEASE}'."
          exit 1
        else
          printf "Runner:  %s\n" "Ubuntu ${DISTRIB_RELEASE} (x86-64)"
        fi

        if [[ "${{ inputs.version }}" == "nightly" ]]; then
          VERSION_IN_URL="nightly"
          VERSION_IN_FILE="${{ steps.variables.outputs.nightly-version }}"

          printf "Version: %s\n" "nightly (${VERSION_IN_FILE})"
        elif [[ "${{ inputs.version }}" == "latest" ]]; then
          VERSION_IN_URL="${{ steps.variables.outputs.nightly-version }}"
          VERSION_IN_FILE="${{ steps.variables.outputs.nightly-version }}"

          printf "Version: %s\n" "latest (${VERSION_IN_FILE})"
        elif [[ "${{ inputs.version }}" =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
          VERSION_IN_URL="${{ inputs.version }}"
          VERSION_IN_FILE="${{ inputs.version }}"

          printf "Version: %s\n" "${{ inputs.version }}"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported GHDL version '${{ inputs.version }}'."
          exit 1
        fi

        if [[ "${{ inputs.backend }}" =~ ^mcode|llvm(-jit)?|gcc$ ]]; then
          printf "Backend: %s\n" "${{ inputs.backend }}"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported GHDL backend '${{ inputs.backend }}'."
          exit 1
        fi

        (
          printf "Creating installation directory '${{ inputs.install-directory }}' ...\n"
          mkdir -p "${{ inputs.install-directory }}"
          cd "${{ inputs.install-directory }}"

          DOWNLOAD_URL="https://github.com/ghdl/ghdl/releases/download/${VERSION_IN_URL}/ghdl-${{ inputs.backend }}-${VERSION_IN_FILE}-ubuntu${DISTRIB_RELEASE}-x86_64.tar.gz"
          printf "::group::${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "Downloading asset and extracting '${DOWNLOAD_URL}' file ..."
          curl -L "${DOWNLOAD_URL}" | tar -xz --strip-components 1
          printf "::endgroup::\n"

          if [[ "${{ inputs.investigate }}" == "true" ]]; then
            printf "::group::${ANSI_LIGHT_BLUE}%s.${ANSI_NOCOLOR}\n" "Content of '$(pwd)'"
            tree -pash .
            printf "::endgroup::\n"
          fi

          printf "::group::${ANSI_LIGHT_BLUE}%s.${ANSI_NOCOLOR}\n" "Installing dependencies from './ubuntu.requirements' using 'apt-get' ..."
          sudo xargs --no-run-if-empty -a ./ubuntu.requirements -- apt-get install -y --no-install-recommends
          printf "::endgroup::\n"
        )

        printf "Setting environment variable 'GHDL_PREFIX' ...\n"
        tee "${GITHUB_ENV}" <<EOF
        GHDL_PREFIX=$(pwd)/${{ inputs.install-directory }}/lib/ghdl
        EOF

        printf "Adding GHDL to 'PATH' ...\n"
        tee "${GITHUB_PATH}" <<EOF
        $(pwd)/${{ inputs.install-directory }}/bin
        EOF

        printf "Writing step outputs 'xxx' ...\n"

    - name: Download and install GHDL on macOS (${{ runner.arch }})
      id: macOSIntel
      if: runner.os == 'macOS'  && ( runner.arch == 'X64' || runner.arch == 'ARM64' )
      shell: bash
      run: |
        # Download and install GHDL on macOS (${{ runner.arch }})
        ANSI_LIGHT_BLUE="\e[94m"
        ANSI_NOCOLOR=$'\x1b[0m'

        # TODO: check macOS version

        if [[ "${{ runner.arch }}" == "X64" ]]; then
          OS_RELEASE=13
          OS_ARCH=x86_64
        elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
          OS_RELEASE=14
          OS_ARCH=aarch64
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported macOS architecture '${{ runner.arch }}'."
          exit 1
        fi
        printf "macOS:   macOS %s - %s\n" "${OS_RELEASE}" "${OS_ARCH//_/-}"

        if [[ "${{ inputs.version }}" == "nightly" ]]; then
          VERSION_IN_URL="nightly"
          VERSION_IN_FILE="${{ steps.variables.outputs.nightly-version }}"

          printf "Version: %s\n" "nightly (${VERSION_IN_FILE})"
        elif [[ "${{ inputs.version }}" == "latest" ]]; then
          VERSION_IN_URL="${{ steps.variables.outputs.nightly-version }}"
          VERSION_IN_FILE="${{ steps.variables.outputs.nightly-version }}"

          printf "Version: %s\n" "latest (${VERSION_IN_FILE})"
        elif [[ "${{ inputs.version }}" =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
          VERSION_IN_URL="${{ inputs.version }}"
          VERSION_IN_FILE="${{ inputs.version }}"

          printf "Version: %s\n" "${{ inputs.version }}"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported GHDL version '${{ inputs.version }}'."
          exit 1
        fi

        if [[ "${{ inputs.backend }}" =~ ^mcode|llvm(-jit)?$ ]]; then
          printf "Backend: %s\n" "${{ inputs.backend }}"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported GHDL backend '${{ inputs.backend }}'."
          exit 1
        fi

        (
          printf "Creating installation directory '${{ inputs.install-directory }}' ...\n"
          mkdir -p "${{ inputs.install-directory }}"
          cd "${{ inputs.install-directory }}"

          DOWNLOAD_URL="https://github.com/ghdl/ghdl/releases/download/${VERSION_IN_URL}/ghdl-${{ inputs.backend }}-${VERSION_IN_FILE}-macos${OS_RELEASE}-${OS_ARCH}.tar.gz"
          printf "::group::${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "Downloading asset and extracting '${DOWNLOAD_URL}' file ..."
          curl -L "${DOWNLOAD_URL}" | tar -xz --strip-components 1
          printf "::endgroup::\n"

          if [[ "${{ inputs.investigate }}" == "true" ]]; then
            cd bin
            printf "::group::${ANSI_LIGHT_BLUE}%s.${ANSI_NOCOLOR}\n" "Content of '$(pwd)'"

            # tree is not supported on macOS
            # tree -pash .
            ls -lAh .
            printf "::endgroup::\n"
          fi
        )

        printf "Setting environment variable 'GHDL_PREFIX' ...\n"
        tee "${GITHUB_ENV}" <<EOF
        GHDL_PREFIX=$(pwd)/${{ inputs.install-directory }}/lib/ghdl
        EOF

        printf "Adding GHDL to 'PATH' ...\n"
        tee "${GITHUB_PATH}" <<EOF
        $(pwd)/${{ inputs.install-directory }}/bin
        EOF

        printf "Writing step outputs 'xxx' ...\n"

    - name: Download and install GHDL on Windows (native)
      id: Windows
      if: runner.os == 'Windows' && runner.arch == 'X64' && inputs.runtime == ''
      shell: powershell
      run: |
        # Download and install GHDL on Windows (native)
        $BACKEND = "mcode"
        $RUNTIME = "ucrt64"

        if ( "${{ inputs.version }}" -eq "nightly" ) {
          $VERSION_IN_URL =  "nightly"
          $VERSION_IN_FILE = "${{ steps.variables.outputs.nightly-version }}"

          echo "Version: nightly (${VERSION_IN_FILE})"
        } elseif ( "${{ inputs.version }}" -eq "latest" ) {
          $VERSION_IN_URL =  "${{ steps.variables.outputs.nightly-version }}"
          $VERSION_IN_FILE = "${{ steps.variables.outputs.nightly-version }}"

          echo "Version: nightly (${VERSION_IN_FILE})"
        } elseif ( "${{ inputs.version }}" -match '^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$' ) {
          $VERSION_IN_URL =  "${{ inputs.version }}"
          $VERSION_IN_FILE = "${{ inputs.version }}"

          echo "Version: ${{ inputs.version }}"
        } else {
          echo "::error title=setup-ghdl::Unsupported GHDL version '${{ inputs.version }}'."
          exit 1
        }

        if ( "${{ inputs.backend }}" -eq "mcode" ) {
          echo "Backend: ${{ inputs.backend }}"
        } else {
          echo "::error title=setup-ghdl::Unsupported GHDL backend '${{ inputs.backend }}'."
          exit 1
        }

        echo "Creating installation directory '${{ inputs.install-directory }}' ..."
        mkdir "${{ inputs.install-directory }}" | Out-Null
        cd "${{ inputs.install-directory }}"

        $DOWNLOAD_URL = "https://github.com/ghdl/ghdl/releases/download/${VERSION_IN_URL}/ghdl-${BACKEND}-${VERSION_IN_FILE}-${RUNTIME}.zip"
        echo "Downloading asset from '${DOWNLOAD_URL}' ..."
        curl "${DOWNLOAD_URL}" -o ghdl.zip

        echo "Extracting zip file 'ghdl.zip' ..."
        Expand-Archive -Path "ghdl.zip" -DestinationPath "."

        echo "Removing zip file 'ghdl.zip' ..."
        rm "ghdl.zip"

        echo "Setting environment variable 'GHDL_PREFIX' ..."
        echo "GHDL_PREFIX=$($(pwd).Path)\lib\ghdl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        echo "Adding GHDL to 'PATH' ..."
        echo "$($(pwd).Path)\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Download and install GHDL on Windows + MSYS2 (x86-64)
      id: MSYS2
      if: runner.os == 'Windows' && runner.arch == 'X64' && ( inputs.runtime == 'mingw64' || inputs.runtime == 'ucrt64' )
      shell: 'msys2 {0}'
      run: |
        # Download and install GHDL on Windows + MSYS2 (x86-64)
        ANSI_LIGHT_RED=$'\x1b[91m'
        ANSI_LIGHT_GREEN=$'\x1b[92m'
        ANSI_LIGHT_BLUE="\e[94m"
        ANSI_NOCOLOR=$'\x1b[0m'

        if [[ ${{ inputs.runtime }} == "mingw64" ]]; then
          RUNTIME=""
        elif [[ ${{ inputs.runtime }} == "ucrt64" ]]; then
          RUNTIME="ucrt-"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported MSYS 2 runtime '${{ inputs.runtime }}'."
          exit 1
        fi
        printf "MSYS2:   %s\n" "${{ inputs.runtime }}"

        if [[ "${{ inputs.version }}" == "nightly" ]]; then
          VERSION_IN_URL="nightly"
          VERSION_IN_FILE="${{ steps.variables.outputs.nightly-version-msys2 }}"

          printf "Version: %s\n" "nightly (${VERSION_IN_FILE})"
        elif [[ "${{ inputs.version }}" == "latest" ]]; then
          VERSION_IN_URL="${{ steps.variables.outputs.nightly-version }}"
          VERSION_IN_FILE="${{ steps.variables.outputs.nightly-version-msys2 }}"

          printf "Version: %s\n" "nightly (${VERSION_IN_FILE})"
        elif [[ "${{ inputs.version }}" =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
          VERSION_IN_URL="${{ inputs.version }}"
          VERSION_IN_FILE="${{ inputs.version }}"

          printf "Version: %s\n" "${{ inputs.version }}"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported GHDL version '${{ inputs.version }}'."
          exit 1
        fi

        if [[ "${{ inputs.backend }}" =~ ^mcode|llvm(-jit)?$ ]]; then
          printf "Backend: %s\n" "${{ inputs.backend }}"
        else
          printf "::error title=%s::%s\n" "setup-ghdl" "Unsupported GHDL backend '${{ inputs.backend }}'."
          exit 1
        fi

        DOWNLOAD_URL="https://github.com/ghdl/ghdl/releases/download/${VERSION_IN_URL}/mingw-w64-${RUNTIME}x86_64-ghdl-${{ inputs.backend }}-${VERSION_IN_FILE}-any.pkg.tar.zst"
        printf "::group::${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "Downloading asset from '${DOWNLOAD_URL}' ..."
        curl -L "${DOWNLOAD_URL}" -o ghdl.pkg.tar.zst
        printf "::endgroup::\n"

        printf "::group::${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "Installing 'ghdl.pkg.tar.zst' file ..."
        pacman -U --noconfirm ghdl.pkg.tar.zst
        printf "::endgroup::\n"

        printf "Deleting '%s' ... " "ghdl.pkg.tar.zst"
        rm "ghdl.pkg.tar.zst"
        if [[ $? -eq 0 ]]; then
          printf "%s\n" "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
        else
          printf "%s\n" "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
          printf "::warning title=%s::%s\n" "setup-ghdl" "Failed to remove 'ghdl.pkg.tar.zst'."
        fi

        printf "Setting environment variable 'GHDL_PREFIX' ...\n"
        tee "${GITHUB_ENV}" <<EOF
        GHDL_PREFIX=$(realpath $(dirname $(which ghdl))/../lib/ghdl)
        EOF
