name: Verification of setup-ghdl

on:
  push:
  workflow_dispatch:

jobs:
  Setup-GHDL-Nightly:
    name: ${{ matrix.os.icon }} Setup GHDL ${{ matrix.os.backend }} on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.image }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'mcode'}
          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'llvm'}
          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'llvm-jit'}
          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'gcc'}
          - {'icon': '🍎',   'name': 'macOS',   'image': 'macos-13',     'runtime': '',        'backend': 'mcode'}
          - {'icon': '🍎',   'name': 'macOS',   'image': 'macos-13',     'runtime': '',        'backend': 'llvm'}
          - {'icon': '🍏',   'name': 'macOS',   'image': 'macos-14',     'runtime': '',        'backend': 'llvm'}
          - {'icon': '🪟',   'name': 'Windows', 'image': 'windows-2022', 'runtime': '',        'backend': 'mcode'}
          - {'icon': '🪟🟦', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'mingw64', 'backend': 'mcode'}
          - {'icon': '🪟🟦', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'mingw64', 'backend': 'llvm'}
          - {'icon': '🪟🟦', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'mingw64', 'backend': 'llvm-jit'}
          - {'icon': '🪟🟨', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'ucrt64',  'backend': 'mcode'}
          - {'icon': '🪟🟨', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'ucrt64',  'backend': 'llvm'}
          - {'icon': '🪟🟨', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'ucrt64',  'backend': 'llvm-jit'}
    defaults:
      run:
        shell: bash

    steps:
      - name: 🟦 Setup MSYS2 for ${{ matrix.os.runtime }}
        uses: msys2/setup-msys2@v2
        if: matrix.os.runtime != ''
        with:
          msystem: ${{ matrix.os.runtime }}
          update: true

      - name: Setup GHDL ${{ matrix.os.backend }}
        uses: paebbels/setup-ghdl@main
        with:
          version: nightly
          backend: ${{ matrix.os.backend }}
          runtime: ${{ matrix.os.runtime }}
          investigate: true

      - name: Verify on Linux and macOS
        if: matrix.os.name == 'Ubuntu' || matrix.os.name == 'macOS'
        run: |
          ghdl --version

      - name: Verify on Windows + MSYS2
        if: matrix.os.name == 'Windows' && matrix.os.runtime != ''
        shell: 'msys2 {0}'
        run: |
          ghdl --version
