# The MIT License (MIT)
#
# Copyright © 2024 The GHDL Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the “Software”), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
name: Verification of setup-ghdl

on:
  push:
  workflow_dispatch:

jobs:
  Setup-GHDL-Nightly:
    name: ${{ matrix.os.icon }} Setup GHDL ${{ matrix.os.backend }} on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.image }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'mcode'}
#          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'llvm'}
#          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'llvm-jit'}
#          - {'icon': '🐧',   'name': 'Ubuntu',  'image': 'ubuntu-24.04', 'runtime': '',        'backend': 'gcc'}
#          - {'icon': '🍎',   'name': 'macOS',   'image': 'macos-13',     'runtime': '',        'backend': 'mcode'}
#          - {'icon': '🍎',   'name': 'macOS',   'image': 'macos-13',     'runtime': '',        'backend': 'llvm'}
#          - {'icon': '🍏',   'name': 'macOS',   'image': 'macos-14',     'runtime': '',        'backend': 'llvm'}
          - {'icon': '🪟',   'name': 'Windows', 'image': 'windows-2022', 'runtime': '',        'backend': 'mcode'}
#          - {'icon': '🪟🟦', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'mingw64', 'backend': 'mcode'}
#          - {'icon': '🪟🟦', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'mingw64', 'backend': 'llvm'}
#          - {'icon': '🪟🟦', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'mingw64', 'backend': 'llvm-jit'}
#          - {'icon': '🪟🟨', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'ucrt64',  'backend': 'mcode'}
#          - {'icon': '🪟🟨', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'ucrt64',  'backend': 'llvm'}
#          - {'icon': '🪟🟨', 'name': 'Windows', 'image': 'windows-2022', 'runtime': 'ucrt64',  'backend': 'llvm-jit'}
    defaults:
      run:
        shell: bash

    steps:
      - name: 🟦 Setup MSYS2 for ${{ matrix.os.runtime }}
        uses: msys2/setup-msys2@v2
        if: matrix.os.runtime != ''
        with:
          msystem: ${{ matrix.os.runtime }}
          update: true

      - name: Setup GHDL ${{ matrix.os.backend }}
        uses: paebbels/setup-ghdl@dev
        with:
          version: nightly
          backend: ${{ matrix.os.backend }}
          runtime: ${{ matrix.os.runtime }}
          investigate: true

      - name: Verify on Linux, macOS or Windows (native)
        if: matrix.os.name == 'Ubuntu' || matrix.os.name == 'macOS'
        run: |
          ghdl --version

      - name: Verify on Linux, macOS or Windows (native)
        if: matrix.os.name == 'Windows' && matrix.os.runtime == ''
        shell: powershell
        run: |
          ghdl --version

      - name: Verify on Windows + MSYS2
        if: matrix.os.name == 'Windows' && matrix.os.runtime != ''
        shell: 'msys2 {0}'
        run: |
          ghdl --version
